/*
 * ChuTi.java
 *
 * Created on __DATE__, __TIME__
 */

package p1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.util.ArrayList;

import org.omg.CORBA.portable.InputStream;



import com.csvreader.CsvWriter;

/**
 *
 * @author  __USER__
 */
public class ChuTi extends javax.swing.JFrame {

	/** Creates new form ChuTi */
	public ChuTi() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jFileChooser1 = new javax.swing.JFileChooser();
		jDialog1 = new javax.swing.JDialog();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jTextField8 = new javax.swing.JTextField();
		jTextField9 = new javax.swing.JTextField();
		jTextField10 = new javax.swing.JTextField();
		jTextField11 = new javax.swing.JTextField();
		jTextField12 = new javax.swing.JTextField();
		jTextField13 = new javax.swing.JTextField();
		jTextField14 = new javax.swing.JTextField();
		jTextField15 = new javax.swing.JTextField();
		jTextField16 = new javax.swing.JTextField();
		jTextField17 = new javax.swing.JTextField();
		jTextField18 = new javax.swing.JTextField();
		jTextField19 = new javax.swing.JTextField();
		jTextField20 = new javax.swing.JTextField();
		jTextField21 = new javax.swing.JTextField();
		jTextField22 = new javax.swing.JTextField();
		jTextField23 = new javax.swing.JTextField();
		jTextField24 = new javax.swing.JTextField();
		jTextField25 = new javax.swing.JTextField();
		jTextField26 = new javax.swing.JTextField();
		jTextField27 = new javax.swing.JTextField();
		jTextField28 = new javax.swing.JTextField();
		jTextField29 = new javax.swing.JTextField();
		jTextField30 = new javax.swing.JTextField();
		jTextField31 = new javax.swing.JTextField();
		jTextField32 = new javax.swing.JTextField();
		jTextField33 = new javax.swing.JTextField();
		jTextField34 = new javax.swing.JTextField();
		jTextField35 = new javax.swing.JTextField();
		jTextField36 = new javax.swing.JTextField();
		jTextField37 = new javax.swing.JTextField();
		jTextField38 = new javax.swing.JTextField();
		jTextField39 = new javax.swing.JTextField();
		jTextField40 = new javax.swing.JTextField();

		javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(
				jDialog1.getContentPane());
		jDialog1.getContentPane().setLayout(jDialog1Layout);
		jDialog1Layout.setHorizontalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("\u5bfc\u5165\u4e60\u9898\u6587\u4ef6");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jButton1MouseClicked(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jButton2.setText("\u5bfc\u51fa\u7ec3\u4e60\u6587\u4ef6");
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton2MouseClicked(evt);
			}
		});

		jButton3.setText("\u6279\u6539");
		jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton3MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(70, 70, 70)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton2)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton3))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				6,
																				6,
																				6)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jTextField31,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField21,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField11,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								61,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTextField32,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField22,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField12,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								36,
																								Short.MAX_VALUE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTextField33,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField23,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField13,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField3,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								63,
																								Short.MAX_VALUE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTextField34,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField24,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField14,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField4,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								34,
																								Short.MAX_VALUE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTextField35)
																						.addComponent(
																								jTextField25,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField15,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField5,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								59,
																								Short.MAX_VALUE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTextField36,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField26,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField16)
																						.addComponent(
																								jTextField6,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								33,
																								Short.MAX_VALUE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTextField37)
																						.addComponent(
																								jTextField27,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField17,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField7,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								65,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTextField38,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField28,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField18,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField8,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								35,
																								Short.MAX_VALUE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTextField39,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField29)
																						.addComponent(
																								jTextField19,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField9,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								66,
																								Short.MAX_VALUE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jTextField40,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField30,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField20,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField10,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								32,
																								Short.MAX_VALUE))))
										.addContainerGap(652, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(27, 27, 27)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2)
														.addComponent(jButton3))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jTextField2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jTextField3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jTextField4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jTextField5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jTextField6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jTextField7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jTextField8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jTextField9,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jTextField10,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField11,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField12,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField13,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField14,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField15,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField16,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField17,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField18,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField19,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField20,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField21,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField22,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField23,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField24,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField25,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField26,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField27,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField28,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField29,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField30,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField31,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField32,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField33,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField34,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField35,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField36,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField37,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField38,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField39,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField40,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(276, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
   
	
	public ArrayList chuLi(){
		ArrayList<Integer>list=new ArrayList<Integer>();
			if(jTextField1.getText().contains("+"))
		    list.add(Integer.valueOf(jTextField1.getText().substring(0,
				jTextField1.getText().indexOf("+")))+
				Integer.valueOf(jTextField1.getText().substring(
				jTextField1.getText().indexOf("+")+1,
				jTextField1.getText().indexOf("="))));
			if(jTextField1.getText().contains("-"))
				list.add(Integer.valueOf(jTextField1.getText().substring(0,
						jTextField1.getText().indexOf("-")))-
						Integer.valueOf(jTextField1.getText().substring(
						jTextField1.getText().indexOf("-")+1,
						jTextField1.getText().indexOf("="))));
			if(jTextField3.getText().contains("+"))
				list.add(Integer.valueOf(jTextField3.getText().substring(0,
						jTextField3.getText().indexOf("+")))+
						Integer.valueOf(jTextField3.getText().substring(
						jTextField3.getText().indexOf("+")+1,
						jTextField3.getText().indexOf("="))));
			if(jTextField3.getText().contains("-"))
				list.add(Integer.valueOf(jTextField3.getText().substring(0,
						jTextField3.getText().indexOf("-")))-
						Integer.valueOf(jTextField3.getText().substring(
						jTextField3.getText().indexOf("-")+1,
						jTextField3.getText().indexOf("="))));
			if(jTextField5.getText().contains("+"))
				list.add(Integer.valueOf(jTextField5.getText().substring(0,
						jTextField5.getText().indexOf("+")))+
						Integer.valueOf(jTextField5.getText().substring(
						jTextField5.getText().indexOf("+")+1,
						jTextField5.getText().indexOf("="))));
			if(jTextField5.getText().contains("-"))
				list.add(Integer.valueOf(jTextField5.getText().substring(0,
						jTextField5.getText().indexOf("-")))-
						Integer.valueOf(jTextField5.getText().substring(
						jTextField5.getText().indexOf("-")+1,
						jTextField5.getText().indexOf("="))));
			if(jTextField7.getText().contains("+"))
				list.add(Integer.valueOf(jTextField7.getText().substring(0,
						jTextField7.getText().indexOf("+")))+
						Integer.valueOf(jTextField7.getText().substring(
						jTextField7.getText().indexOf("+")+1,
						jTextField7.getText().indexOf("="))));
			if(jTextField7.getText().contains("-"))
				list.add(Integer.valueOf(jTextField7.getText().substring(0,
						jTextField7.getText().indexOf("-")))-
						Integer.valueOf(jTextField7.getText().substring(
						jTextField7.getText().indexOf("-")+1,
						jTextField7.getText().indexOf("="))));
			if(jTextField9.getText().contains("+"))
				list.add(Integer.valueOf(jTextField9.getText().substring(0,
						jTextField9.getText().indexOf("+")))+
						Integer.valueOf(jTextField9.getText().substring(
						jTextField9.getText().indexOf("+")+1,
						jTextField9.getText().indexOf("="))));
			if(jTextField9.getText().contains("-"))
				list.add(Integer.valueOf(jTextField9.getText().substring(0,
						jTextField9.getText().indexOf("-")))-
						Integer.valueOf(jTextField9.getText().substring(
						jTextField9.getText().indexOf("-")+1,
						jTextField9.getText().indexOf("="))));
			if(jTextField11.getText().contains("+"))
			    list.add(Integer.valueOf(jTextField11.getText().substring(0,
					jTextField11.getText().indexOf("+")))+
					Integer.valueOf(jTextField11.getText().substring(
					jTextField11.getText().indexOf("+")+1,
					jTextField11.getText().indexOf("="))));
				if(jTextField11.getText().contains("-"))
					list.add(Integer.valueOf(jTextField11.getText().substring(0,
							jTextField11.getText().indexOf("-")))-
							Integer.valueOf(jTextField11.getText().substring(
							jTextField11.getText().indexOf("-")+1,
							jTextField11.getText().indexOf("="))));
				if(jTextField13.getText().contains("+"))
					list.add(Integer.valueOf(jTextField13.getText().substring(0,
							jTextField13.getText().indexOf("+")))+
							Integer.valueOf(jTextField13.getText().substring(
							jTextField13.getText().indexOf("+")+1,
							jTextField13.getText().indexOf("="))));
				if(jTextField13.getText().contains("-"))
					list.add(Integer.valueOf(jTextField13.getText().substring(0,
							jTextField13.getText().indexOf("-")))-
							Integer.valueOf(jTextField13.getText().substring(
							jTextField13.getText().indexOf("-")+1,
							jTextField13.getText().indexOf("="))));
				if(jTextField15.getText().contains("+"))
					list.add(Integer.valueOf(jTextField15.getText().substring(0,
							jTextField15.getText().indexOf("+")))+
							Integer.valueOf(jTextField15.getText().substring(
							jTextField15.getText().indexOf("+")+1,
							jTextField15.getText().indexOf("="))));
				if(jTextField15.getText().contains("-"))
					list.add(Integer.valueOf(jTextField15.getText().substring(0,
							jTextField15.getText().indexOf("-")))-
							Integer.valueOf(jTextField15.getText().substring(
							jTextField15.getText().indexOf("-")+1,
							jTextField15.getText().indexOf("="))));
				if(jTextField17.getText().contains("+"))
					list.add(Integer.valueOf(jTextField17.getText().substring(0,
							jTextField17.getText().indexOf("+")))+
							Integer.valueOf(jTextField17.getText().substring(
							jTextField17.getText().indexOf("+")+1,
							jTextField17.getText().indexOf("="))));
				if(jTextField17.getText().contains("-"))
					list.add(Integer.valueOf(jTextField17.getText().substring(0,
							jTextField17.getText().indexOf("-")))-
							Integer.valueOf(jTextField17.getText().substring(
							jTextField17.getText().indexOf("-")+1,
							jTextField17.getText().indexOf("="))));
				if(jTextField19.getText().contains("+"))
					list.add(Integer.valueOf(jTextField19.getText().substring(0,
							jTextField19.getText().indexOf("+")))+
							Integer.valueOf(jTextField19.getText().substring(
							jTextField19.getText().indexOf("+")+1,
							jTextField19.getText().indexOf("="))));
				if(jTextField19.getText().contains("-"))
					list.add(Integer.valueOf(jTextField19.getText().substring(0,
							jTextField19.getText().indexOf("-")))-
							Integer.valueOf(jTextField19.getText().substring(
							jTextField19.getText().indexOf("-")+1,
							jTextField19.getText().indexOf("="))));
				
				if(jTextField21.getText().contains("+"))
				    list.add(Integer.valueOf(jTextField21.getText().substring(0,
						jTextField21.getText().indexOf("+")))+
						Integer.valueOf(jTextField21.getText().substring(
						jTextField21.getText().indexOf("+")+1,
						jTextField21.getText().indexOf("="))));
					if(jTextField21.getText().contains("-"))
						list.add(Integer.valueOf(jTextField21.getText().substring(0,
								jTextField21.getText().indexOf("-")))-
								Integer.valueOf(jTextField21.getText().substring(
								jTextField21.getText().indexOf("-")+1,
								jTextField21.getText().indexOf("="))));
					if(jTextField23.getText().contains("+"))
						list.add(Integer.valueOf(jTextField23.getText().substring(0,
								jTextField23.getText().indexOf("+")))+
								Integer.valueOf(jTextField23.getText().substring(
								jTextField23.getText().indexOf("+")+1,
								jTextField23.getText().indexOf("="))));
					if(jTextField23.getText().contains("-"))
						list.add(Integer.valueOf(jTextField23.getText().substring(0,
								jTextField23.getText().indexOf("-")))-
								Integer.valueOf(jTextField23.getText().substring(
								jTextField23.getText().indexOf("-")+1,
								jTextField23.getText().indexOf("="))));
					if(jTextField25.getText().contains("+"))
						list.add(Integer.valueOf(jTextField25.getText().substring(0,
								jTextField25.getText().indexOf("+")))+
								Integer.valueOf(jTextField25.getText().substring(
								jTextField25.getText().indexOf("+")+1,
								jTextField25.getText().indexOf("="))));
					if(jTextField25.getText().contains("-"))
						list.add(Integer.valueOf(jTextField25.getText().substring(0,
								jTextField25.getText().indexOf("-")))-
								Integer.valueOf(jTextField25.getText().substring(
								jTextField25.getText().indexOf("-")+1,
								jTextField25.getText().indexOf("="))));
					if(jTextField27.getText().contains("+"))
						list.add(Integer.valueOf(jTextField27.getText().substring(0,
								jTextField27.getText().indexOf("+")))+
								Integer.valueOf(jTextField27.getText().substring(
								jTextField27.getText().indexOf("+")+1,
								jTextField27.getText().indexOf("="))));
					if(jTextField27.getText().contains("-"))
						list.add(Integer.valueOf(jTextField27.getText().substring(0,
								jTextField27.getText().indexOf("-")))-
								Integer.valueOf(jTextField27.getText().substring(
								jTextField27.getText().indexOf("-")+1,
								jTextField27.getText().indexOf("="))));
					if(jTextField29.getText().contains("+"))
						list.add(Integer.valueOf(jTextField29.getText().substring(0,
								jTextField29.getText().indexOf("+")))+
								Integer.valueOf(jTextField29.getText().substring(
								jTextField29.getText().indexOf("+")+1,
								jTextField29.getText().indexOf("="))));
					if(jTextField29.getText().contains("-"))
						list.add(Integer.valueOf(jTextField29.getText().substring(0,
								jTextField29.getText().indexOf("-")))-
								Integer.valueOf(jTextField29.getText().substring(
								jTextField29.getText().indexOf("-")+1,
								jTextField29.getText().indexOf("="))));
			
					if(jTextField31.getText().contains("+"))
					    list.add(Integer.valueOf(jTextField31.getText().substring(0,
							jTextField31.getText().indexOf("+")))+
							Integer.valueOf(jTextField31.getText().substring(
							jTextField31.getText().indexOf("+")+1,
							jTextField31.getText().indexOf("="))));
						if(jTextField31.getText().contains("-"))
							list.add(Integer.valueOf(jTextField31.getText().substring(0,
									jTextField31.getText().indexOf("-")))-
									Integer.valueOf(jTextField31.getText().substring(
									jTextField31.getText().indexOf("-")+1,
									jTextField31.getText().indexOf("="))));
						if(jTextField33.getText().contains("+"))
							list.add(Integer.valueOf(jTextField33.getText().substring(0,
									jTextField33.getText().indexOf("+")))+
									Integer.valueOf(jTextField33.getText().substring(
									jTextField33.getText().indexOf("+")+1,
									jTextField33.getText().indexOf("="))));
						if(jTextField33.getText().contains("-"))
							list.add(Integer.valueOf(jTextField33.getText().substring(0,
									jTextField33.getText().indexOf("-")))-
									Integer.valueOf(jTextField33.getText().substring(
									jTextField33.getText().indexOf("-")+1,
									jTextField33.getText().indexOf("="))));
						if(jTextField35.getText().contains("+"))
							list.add(Integer.valueOf(jTextField35.getText().substring(0,
									jTextField35.getText().indexOf("+")))+
									Integer.valueOf(jTextField35.getText().substring(
									jTextField35.getText().indexOf("+")+1,
									jTextField35.getText().indexOf("="))));
						if(jTextField35.getText().contains("-"))
							list.add(Integer.valueOf(jTextField35.getText().substring(0,
									jTextField35.getText().indexOf("-")))-
									Integer.valueOf(jTextField35.getText().substring(
									jTextField35.getText().indexOf("-")+1,
									jTextField35.getText().indexOf("="))));
						if(jTextField37.getText().contains("+"))
							list.add(Integer.valueOf(jTextField37.getText().substring(0,
									jTextField37.getText().indexOf("+")))+
									Integer.valueOf(jTextField37.getText().substring(
									jTextField37.getText().indexOf("+")+1,
									jTextField37.getText().indexOf("="))));
						if(jTextField37.getText().contains("-"))
							list.add(Integer.valueOf(jTextField37.getText().substring(0,
									jTextField37.getText().indexOf("-")))-
									Integer.valueOf(jTextField37.getText().substring(
									jTextField37.getText().indexOf("-")+1,
									jTextField37.getText().indexOf("="))));
						if(jTextField39.getText().contains("+"))
							list.add(Integer.valueOf(jTextField39.getText().substring(0,
									jTextField39.getText().indexOf("+")))+
									Integer.valueOf(jTextField39.getText().substring(
									jTextField39.getText().indexOf("+")+1,
									jTextField39.getText().indexOf("="))));
						if(jTextField39.getText().contains("-"))
							list.add(Integer.valueOf(jTextField39.getText().substring(0,
									jTextField39.getText().indexOf("-")))-
									Integer.valueOf(jTextField39.getText().substring(
									jTextField39.getText().indexOf("-")+1,
									jTextField39.getText().indexOf("="))));
						return list;
				}
	//批改练习文件
	private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		
		ArrayList<Integer>list=new ArrayList<Integer>();
		int correct=0;
		int error=0;
		list=chuLi();
		for(int i=0;i<20;i++){
		   
		   System.out.println(this.lstFile.get(i)+"\t"+"\t"+list.get(i));
			if((lstFile.get(i)).equals(String.valueOf(list.get(i)))){ correct++;
			}
			else error++;
		}
		Helpter.tiShu=list.size();
		Helpter.error=error;
		Helpter.correct=correct;
	Judge jd=new Judge(this,true);
	jd.setLocationRelativeTo(null);
	jd.setVisible(true);
	

	}

	//导出练习文件
	String exerciseName = null;
	ArrayList<String> lstFile=null;
	private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.lstFile = new ArrayList<String>();

		File f = new File("d:\\练习文件");
		if (!f.exists() && !f.isDirectory()) {
			System.out.println("//不存在");
			//创建路径，如果父路径和子路径都不存在就全部创建
			f.mkdirs();
		} else {
			System.out.println("//目录存在");
		}
		System.out.println("请输入本次练习的结果：");// 提示用户输入字符串
		String pathCSVWrite = "d:\\练习文件\\" + "practice_" + exerciseName;

		try {
			//利用输入流将输入的结果放在lstFile中
			lstFile.add((jTextField2.getText().equals("")) ? ("-1")
					: jTextField2.getText());
			lstFile.add((jTextField4.getText().equals("")) ? ("-1")
					: jTextField4.getText());
			lstFile.add((jTextField6.getText().equals("")) ? ("-1")
					: jTextField6.getText());
			lstFile.add((jTextField8.getText().equals("")) ? ("-1")
					: jTextField8.getText());
			lstFile.add((jTextField10.getText().equals("")) ? ("-1")
					: jTextField10.getText());

			lstFile.add((jTextField12.getText().equals("")) ? ("-1")
					: jTextField12.getText());
			lstFile.add((jTextField14.getText().equals("")) ? ("-1")
					: jTextField14.getText());
			lstFile.add((jTextField16.getText().equals("")) ? ("-1")
					: jTextField16.getText());
			lstFile.add((jTextField18.getText().equals("")) ? ("-1")
					: jTextField18.getText());
			lstFile.add((jTextField20.getText().equals("")) ? ("-1")
					: jTextField20.getText());

			lstFile.add((jTextField22.getText().equals("")) ? ("-1")
					: jTextField22.getText());
			lstFile.add((jTextField24.getText().equals("")) ? ("-1")
					: jTextField24.getText());
			lstFile.add((jTextField26.getText().equals("")) ? ("-1")
					: jTextField26.getText());
			lstFile.add((jTextField28.getText().equals("")) ? ("-1")
					: jTextField28.getText());
			lstFile.add((jTextField30.getText().equals("")) ? ("-1")
					: jTextField30.getText());

			lstFile.add((jTextField32.getText().equals("")) ? ("-1")
					: jTextField32.getText());
			lstFile.add((jTextField34.getText().equals("")) ? ("-1")
					: jTextField34.getText());
			lstFile.add((jTextField36.getText().equals("")) ? ("-1")
					: jTextField36.getText());
			lstFile.add((jTextField38.getText().equals("")) ? ("-1")
					: jTextField38.getText());
			lstFile.add((jTextField40.getText().equals("")) ? ("-1")
					: jTextField40.getText());

			CsvWriter csvWriter = new CsvWriter(pathCSVWrite, ',', Charset
					.forName("utf-8"));
			//写入csv文件，每行写5个
			for (int i = 0; i < lstFile.size(); i = i + 5) {
				String[] csvContent = { lstFile.get(i), lstFile.get(i + 1),
						lstFile.get(i + 2), lstFile.get(i + 3),
						lstFile.get(i + 4),

				};
				csvWriter.writeRecord(csvContent);
			}
			csvWriter.close();
			System.out.println("--------------------已完成写入操作--------------");

		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	//导入习题文件
	private void jButton1MouseClicked(java.awt.event.MouseEvent evt)
			throws IOException {
		// TODO add your handling code here:
		int flag = jFileChooser1.showOpenDialog(this);
		if (flag == jFileChooser1.APPROVE_OPTION) {//点的确定
			File f = jFileChooser1.getSelectedFile();
			BufferedReader br = new BufferedReader(new FileReader(f));
			this.exerciseName = f.getName();
			String[][] data = new String[1024][5];
			int j = 0;
			String s = null;
			s = br.readLine();
			while (s != null) {
				String s1 = s.substring(s.indexOf(",") + 1);
				String s2 = s1.substring(s1.indexOf(",") + 1);
				String s3 = s2.substring(s2.indexOf(",") + 1);
				String s4 = s3.substring(s3.indexOf(",") + 1);
				data[j][0] = s.substring(0, s.indexOf(","));
				data[j][1] = s1.substring(0, s1.indexOf(","));
				data[j][2] = s2.substring(0, s2.indexOf(","));
				data[j][3] = s3.substring(0, s3.indexOf(","));
				data[j][4] = s4;
				System.out.println(data[j][0]);
				System.out.println(data[j][1]);
				System.out.println(data[j][2]);
				System.out.println(data[j][3]);
				System.out.println(data[j][4]);
				s = br.readLine();

				if (j == 0) {
					jTextField1.setText(data[j][0]);
					jTextField3.setText(data[j][1]);
					jTextField5.setText(data[j][2]);
					jTextField7.setText(data[j][3]);
					jTextField9.setText(data[j][4]);

				}
				if (j == 1) {
					jTextField11.setText(data[j][0]);
					jTextField13.setText(data[j][1]);
					jTextField15.setText(data[j][2]);
					jTextField17.setText(data[j][3]);
					jTextField19.setText(data[j][4]);

				}
				if (j == 2) {
					jTextField21.setText(data[j][0]);
					jTextField23.setText(data[j][1]);
					jTextField25.setText(data[j][2]);
					jTextField27.setText(data[j][3]);
					jTextField29.setText(data[j][4]);

				}
				if (j == 3) {
					jTextField31.setText(data[j][0]);
					jTextField33.setText(data[j][1]);
					jTextField35.setText(data[j][2]);
					jTextField37.setText(data[j][3]);
					jTextField39.setText(data[j][4]);

				}
				j += 1;
			}

			br.close();

		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChuTi().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JDialog jDialog1;
	private javax.swing.JFileChooser jFileChooser1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField jTextField12;
	private javax.swing.JTextField jTextField13;
	private javax.swing.JTextField jTextField14;
	private javax.swing.JTextField jTextField15;
	private javax.swing.JTextField jTextField16;
	private javax.swing.JTextField jTextField17;
	private javax.swing.JTextField jTextField18;
	private javax.swing.JTextField jTextField19;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField20;
	private javax.swing.JTextField jTextField21;
	private javax.swing.JTextField jTextField22;
	private javax.swing.JTextField jTextField23;
	private javax.swing.JTextField jTextField24;
	private javax.swing.JTextField jTextField25;
	private javax.swing.JTextField jTextField26;
	private javax.swing.JTextField jTextField27;
	private javax.swing.JTextField jTextField28;
	private javax.swing.JTextField jTextField29;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField30;
	private javax.swing.JTextField jTextField31;
	private javax.swing.JTextField jTextField32;
	private javax.swing.JTextField jTextField33;
	private javax.swing.JTextField jTextField34;
	private javax.swing.JTextField jTextField35;
	private javax.swing.JTextField jTextField36;
	private javax.swing.JTextField jTextField37;
	private javax.swing.JTextField jTextField38;
	private javax.swing.JTextField jTextField39;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField40;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	// End of variables declaration//GEN-END:variables

}